ACUERDO DEL USUARIO DEL SITIO WEB "REDVOISS.NET"

EL USO DEL SITIO WEB “REDVOISS.NET” Y DE TODOS LOS SERVICIOS HABILITADOS EN ÉL, ESTÁN SUJETOS AL SIGUIENTE ACUERDO DE TÉRMINOS Y CONDICIONES (EL “ACUERDO”), EL CUAL ES ACEPTADO POR LOS USUARIOS, POR EL SOLO HECHO DE ACCEDER AL SITIO “REDVOISS.NET” O DE USAR SUS SERVICIOS.
                          VOISSNET CLOUD SERVICES S.A., en adelante REDVOISS, es una empresa que se dedica a prestar diversos servicios de telecomunicaciones a través de redes IP públicas y privadas. En virtud de lo anterior, cuenta con la tecnología necesaria para prestar un servicio que permite, a los usuarios que lo contraten, comunicación telefónica y otros servicios de telecomunicaciones a través de redes IP públicas y privadas.
                          
Las partes dejan expresa constancia que el servicio que presta REDVOISS no es un servicio público telefónico, según lo define la Ley General de Telecomunicaciones de Chile, no siendo REDVOISS titular de concesión alguna al amparo de dicha ley. En consecuencia, el Cliente declara conocer y aceptar que el servicio de transmisión de datos de voz a través de Internet prestado por REDVOISS no está regido por dicha ley ni por sus normas complementarias, particularmente en lo que se refiere a la calidad de servicio exigible.
"Redvoiss.net" es un sitio en Internet (en adelante el "Sitio") por medio del cual REDVOISS, pretende facilitar las comunicaciones electrónicas, sirviendo de nexo entre dos o más usuarios, enlazando a través de la plataforma de REDVOISS las comunicaciones permitiendo a un usuario, que puede o no ser el Cliente, recibir comunicaciones vía internet de otro usuario de la red, desde la telefonía o mensajería de texto (en adelante, el “Servicio”).
Para los efectos de este servicio se entenderá por " Cliente" la persona natural o jurídica que contrata el Servicio de REDVOISS, y por "Usuario (s)" la persona natural que utiliza los servicios de REDVOISS y que puede utilizar lo contratado por Cliente, pudiendo ambos ser la misma persona. Para dichos efectos, quien efectúa la comunicación de salida o envía el mensaje a través de la plataforma de REDVOISS debe ser el Cliente o los usuarios habilitados por el Cliente para ello.
Lea atentamente este Acuerdo para obtener acceso o poder utilizar el Sitio, el software habilitado por REDVOISS para prestar el Servicio (en adelante, el “Software”), o el Servicio. Usted acuerda cumplir con todos los términos y condiciones expresados en este documento. Si no acuerda cumplir con estos términos y condiciones, no puede tener acceso ni utilizar el Sitio el Software o el Servicio. 
REDVOISS está facultada para modificar este Acuerdo en cualquier momento, sin previo aviso, y tales modificaciones se considerarán vigentes inmediatamente después del anuncio del Acuerdo modificado. Usted se compromete a revisar periódicamente el Acuerdo para mantenerse informado sobre tales modificaciones. El acceso o uso del Sitio, del Software o del Servicio valdrá como aceptación concluyente de todos los términos de este Acuerdo y sus modificaciones, sin necesidad de manifestación expresa o comunicación alguna a REDVOISS.

Condiciones generales de uso del Sitio:

1. El acceso al Sitio permite dos servicios: por una parte, el servicio de comunicación entre usuarios (que pueden ser o no Clientes, debiendo ser Cliente o usuario habilitado por el Cliente, el usuario que inicia la comunicación) a través de un teléfono IP o centrales telefónicas, según sea la modalidad que haya elegido. Por otro lado, el servicio de mensajería de texto, que permitirá establecer comunicaciones a través de la red celular, en ambos servicios usted podrá hacer uso del Software de "redvoiss.net" y de todos aquellos documentos, actualizaciones e innovaciones que sean provistas periódicamente por "redvoiss.net". 

2. Ni REDVOISS ni su sitio "redvoiss.net" otorgan garantía alguna, representación o respaldo explícito o implícito asociado al uso de su Software de comunicación, relacionadas con el Servicio, ni con cualquier transacción efectuada a través del Servicio o de Internet en general. Ni REDVOISS ni "redvoiss.net" asumen, por consiguiente, responsabilidad alguna por costos o daños que surjan ya sea en forma directa o indirecta, de tal uso. Asimismo, ni "redvoiss.net" ni REDVOISS pueden garantizar y, en efecto no lo hacen, que los archivos disponibles para descarga desde el Sitio no estén infectados con virus, gusanos, caballos de Troya o cualquier otro código que manifieste propiedades contaminantes o destructivas. Usted es totalmente responsable de tomar las precauciones necesarias para garantizar que lo que seleccione para su uso propio esté libre de virus, gusanos, caballos de Troya y de otros elementos de naturaleza destructiva.
3. Es su responsabilidad implementar suficientes procedimientos y puntos de verificación para satisfacer sus requisitos personales en lo que respecta a la precisión de entrada y salida de datos y para mantener medios externos al Sitio para la reconstrucción de cualquier dato perdido. Usted asume toda responsabilidad y riesgo por el uso del Sitio, el Software, el Servicio e Internet. Todos los servicios que proporciona REDVOISS y "redvoiss.net" se suministran "tal cual son".

4. El Sitio podría contener vínculos con otros sitios ajenos a "redvoiss.net". REDVOISS no controla ni respalda el contenido de los sitios web de terceros. REDVOISS no se hace responsable por los vínculos ligados al Sitio ni se responsabiliza por las prácticas de éstos, ni por su contenido, ni por sus actualizaciones, ni modificaciones. REDVOISS no se hace responsable de los efectos o daños que ello pudiera causar en el PC de los Usuarios. "redvoiss.net" le proporciona vínculos con otros sitios solo a modo de conveniencia y la inclusión de cualquiera de ellos no implica que "redvoiss.net" respalde dicho sitio. A su vez, las marcas que aparecen en este Sitio pueden ser marcas de REDVOISS o de terceros que no están asociados a éste, y pueden encontrarse registradas.

5. La veracidad, integridad y oportunidad de la información y de las comunicaciones que se transmitan por medio de "redvoiss.net" es de exclusiva responsabilidad de quienes la proporcionan o emiten. En consecuencia, REDVOISS actúa únicamente como intermediario de la información que recibe de sus Clientes o Usuarios, quienes la utilizarán para los fines que estimen pertinentes. 

6. Ni "Redvoiss.net" ni REDVOISS serán responsables, en ningún caso, de cualquier daño derivado de cualquier uso que se haga del Sitio, el Software o el Servicio, así como tampoco de cualquier daño incidental, consecuencial o indirecto, que incluya, aunque no se limite, a daños por pérdidas de ganancias, interrupción comercial, pérdida de programas o de información, que surja del uso o de deficiencias de uso del Sitio, del Software o del Servicio o de las transacciones descargadas, hipervinculadas desde el Sitio o proporcionadas con el Servicio, aun cuando "redvoiss.net" o sus representantes autorizados hayan sido notificados de tales daños. Ni REDVOISS ni “redvoiss.net” tampoco serán responsables de denuncias atribuibles a errores, omisiones o imprecisiones del Servicio o de los materiales o de cualquier información descargada a través de o hipervinculada desde el Sitio.

7. Ni "redvoiss.net" ni REDVOISS garantizan ni responderán por errores tipográficos, imprecisiones técnicas o defectos tales como distorsiones de sonido, interferencias, variaciones en la calidad de la voz, ni garantizan que éstos vayan a ser corregidos. Asimismo, dado que el Servicio supone la utilización de redes telefónicas o transporte de paquetes IP cuya propiedad, operación y control está fuera del alcance de REDVOISS, éste no se hace responsable de la calidad de la comunicación ni de desperfectos provocados, entre otros, por tiempos de latencia que se produzcan por exceso de tráfico en la red Internet, deficiente calidad de la voz o deficiencias de la conexión ISP.

8. Los Usuarios que deseen usar este Sitio deberán proporcionar a "redvoiss.net" todos los antecedentes personales que se le soliciten con el fin de individualizarlos correctamente, tomar contacto con ellos, conocer su ubicación geográfica y mantener actualizada dicha información.

9. Usted autoriza a "redvoiss.net" y a REDVOISS para hacer uso de la información que le proporcione, para destinarla única y exclusivamente a fines propios de la operación del Sitio tales como fines estadísticos, de investigación de mercado, registro de operaciones y facturación, sin que ello importe violación del derecho a la privacidad y/o propiedad intelectual sobre dicha información. 


10. REDVOISS se reserva todos los derechos de propiedad de nombre corporativo, marca de servicios, logos, nombres y marcas comerciales, sitio Web y nombre de dominio. Se prohíbe su uso por parte de los Usuarios.

11. El Software, los programas, sonidos, imágenes, eslóganes y textos contenidos en los mismos y demás elementos del sitio "redvoiss.net" son de propiedad privada, incluyendo derechos de autor, de propiedad intelectual, patentes, secretos comerciales, por lo que se encuentran protegidos por la normativa vigente, tanto en Chile como en el extranjero.

12. REDVOISS podrá efectuar mejoras, modificaciones o renovar en cualquier momento la información contenida en el Sitio, en el Software o en el Servicio sin necesidad de dar aviso alguno a los Usuarios.

13. El Usuario y/o Cliente será responsable de cualquier suma que hubiere que pagar y que resulte de una violación en la que usted haya incurrido de este Acuerdo. 

14.  Usted podrá poner término a este Acuerdo en cualquier momento, sin previo aviso, siempre y cuando usted no siga haciendo uso del Sitio, el Servicio o el Software. Las obligaciones y estipulaciones de este Acuerdo continuarán en vigencia después de la terminación del mismo.

15. Si "redvoiss.net" o REDVOISS no insisten en hacer valer el cumplimiento estricto de alguna de las provisiones de este Acuerdo, no se interpretará como un abandono de alguna provisión o derecho ni como consentimiento de REDVOISS para el incumplimiento de la provisión o modificación del Acuerdo. Ni el curso de la conducta entre las partes, ni la práctica comercial actuará en pro de la modificación de alguna de las provisiones de este Acuerdo. 

16. "Redvoiss.net" podrá ceder sus derechos y obligaciones bajo este Acuerdo a terceros, en cualquier momento y sin previo aviso.

17. Está prohibido para el Cliente y Usuarios utilizar los Servicios, Software y el Sitio para realizar comunicaciones ficticias que no tengan como propósito realizar efectivamente una comunicación, esto es aquellas que no tengan por destinatario a una persona natural, o en las que intervenga tecnología para efectuar llamadas o para mantenerlas en curso, generando con ello tráfico ficticio o abultado. El Cliente y Usuarios reconocen que dichas prácticas y comunicaciones ficticias son ilegales. Por tanto, REDVOISS y “redvoiss.net” están facultados para cancelar inmediatamente el acceso del Cliente al Sitio, Software y el Servicio, sin derecho a indemnización alguna a favor del Cliente, en caso de observar que el Sitio, Software o Servicio están siendo usados para dar curso a dicho tráfico ficticio. 

18. Confidencialidad: " redvoiss.net " mantendrá bajo confidencialidad las comunicaciones que se realicen por intermedio del Servicio; la información que le proporcionen los Usuarios y Clientes, con las excepciones aquí contempladas; las transacciones que propongan los Clientes o Usuarios, o las que en definitiva celebren a través del Sitio, para lo cual "redvoiss.net" ha adoptado los resguardos necesarios. Sus equipos se encuentran en una zona de acceso restringido a personas con autorización previa, su personal se encuentra obligado a guardar reserva de dicha información y todos los accesos a sus bases de datos se encuentran resguardados por sistemas de seguridad informática que garantizan su integridad y privacidad. Con todo, los Clientes y Usuarios aceptantes de este acuerdo manifiestan estar en conocimiento que la tecnología que se utiliza en Internet y en la telefonía IP aún se encuentra en desarrollo y, que, en consecuencia, es técnicamente posible que puedan producirse pérdidas o filtraciones de información, o interrupciones momentáneas del Servicio, a raíz de la intervención de factores externos que se encuentran fuera del control de "redvoiss.net", por lo que liberan a ésta de toda responsabilidad por la ocurrencia de cualquiera de dichos desperfectos.

19. Derecho de Exclusión: "redvoiss.net" se reserva el derecho de excluir a cualquier persona, empresa o institución que utilice o pretenda usar el Servicio, si infringiere los términos y condiciones de uso del Sitio.

20. Legislación aplicable y jurisdicción. El Servicio se regirá por las normas vigentes en Chile, cualquiera que sea el lugar de residencia o domicilio del CLIENTE o USUARIO. Por consiguiente, quien haga uso de este Sitio, Software o Servicio queda sometido a la jurisdicción y competencia de los Tribunales Ordinarios de Justicia de la ciudad de Santiago de Chile. Cualquier acción, demanda o denuncia dirigida contra REDVOISS o contra "redvoiss.net" por cualquier motivo, causa o razón relacionado con el Sitio, el Servicio o el Software deberá presentarse ante los Tribunales Ordinarios competentes de la ciudad de Santiago dentro de un año de ocurrido el hecho que la motiva.
Cláusula de confidencialidad en línea:
Una de las mayores preocupaciones de "redvoiss.net" es el carácter privado de la información que Usted nos facilita a través del Sitio. Nuestros métodos de confidencialidad fueron pensados a los efectos de maximizar la capacidad de control del uso de su información personal y privada a medida que le brindamos la posibilidad de obtener información útil e interesante, además de productos y servicios. Lea nuestra Cláusula de confidencialidad atentamente. El utilizar este Sitio Web o presentar cualquier tipo de información personal significa que usted está de acuerdo en que REDVOISS, sus filiales y socios recojan y utilicen dicha información. También debe tener en cuenta que éste puede modificar esta Cláusula de confidencialidad de tiempo en tiempo. En caso de que así suceda, anunciaremos toda modificación, de manera que usted deberá revisar el Sitio en forma periódica. El uso continuo de nuestro software, del servicio y de este sitio constituirá su consentimiento a cualquiera de tales modificaciones.

Información - Cómo la obtenemos:
Cuando Usted usa el Sitio, proporcionará información personal a "redvoiss.net", como su nombre, número de teléfono, dirección, dirección de correo electrónico y otra información con la que pueda ser identificado en forma personal. También recogemos información de uso cuando usted nos visita.
La información de uso del Sitio no es información de identificación personal. Por el contrario, describe la manera en que se utiliza y se navega por nuestro sitio, incluyendo la cantidad y frecuencia de visitantes de cada página Web y la duración de su estadía en ellas. La información de uso del Sitio también incluye los nombres de los dominios de los exploradores que visitan nuestro sitio, la hora del día en que lo visitaron y otra información que no es de identificación personal.
"Redvoiss.net" podrá hacer uso de cookies del browser. Utilizamos cookies para mejorar su experiencia de visualización en la Web. Un cookie es un identificador pequeño, parecido a una patente de automóvil. Se trata de trozos de datos enviados por un servidor web a un explorador web que luego podrán ser leídos por ese servidor. Los cookies se utilizan para personalizar su experiencia de visualización. También se utilizan para dirigir las ofertas comerciales y de publicidad que se ajusten a sus intereses personales y para evitar que le muestren publicidades repetidas. Los cookies no se pueden utilizar para obtener datos de su disco duro, su correo electrónico o cualquier otro dato personal. Puede configurar sus preferencias de Internet de manera tal que, cada vez que reciba un cookie, se lo podamos notificar. Entonces, podrá aceptar o rechazar cualquiera de nuestros cookies. Si decide rechazar un cookie, esto puede afectar el rendimiento de nuestro sitio web.

Información - Cómo la utilizamos:
La información recogida por "redvoiss.net" nos permite personalizar el contenido y los servicios que ofrecemos a nuestros CLIENTES. También nos permite hacerle llegar las publicidades de aquellos productos y servicios que se ajustan a sus intereses y gustos.
"Redvoiss.net" utiliza esta información dentro del marco doméstico de la empresa con el objeto de mejorar los servicios que ofrecemos. También podemos combinarla con otro tipo de información sobre Usted que esté disponible en nuestra empresa o que provenga de otras fuentes. Asimismo, podemos compartirla con socios comerciales externos para que nos ayuden a mejorar nuestro servicio y para ofrecerle nuevos productos, servicios y ofertas especiales.
Tenga en cuenta que puede optar, al momento de la inscripción, por no recibir mensajes de correo electrónico de publicidad y promoción, lo que no aplica a correos con informaciones que el cliente debe saber sobre el servicio otorgado por RedVoiss que siempre serán enviados.
También, podemos utilizar información personal para lograr un mejor diseño de nuestro sitio web además de compartirla con los anunciantes.  La información obtenida no será vendida a terceros.
 
Recolección de datos adicionales:
Para algunos servicios del Sitio utilizamos empresas de publicidad externas para mostrar avisos comerciales en nuestro sitio. Estos avisos pueden incluir cookies. Si bien nosotros utilizamos cookies en otras secciones de nuestro sitio web, la empresa de publicidad recoge los cookies recibidos con los avisos. Nosotros no tenemos acceso a dicha información. La empresa de publicidad externa puede utilizar dicha información a los efectos de enviarle avisos en el futuro. 
 
Seguridad:
"Redvoiss.net" ha implementado características de seguridad apropiadas para proteger la información personal de sus clientes y usuarios contra pérdida, uso incorrecto, acceso no autorizado, divulgación y modificación.
No obstante lo anterior, ante la solicitud de un organismo competente o ante cualquier otro requerimiento legal, REDVOISS o "redvoiss.net" podrá revelar información de identificación personal además de proporcionar estadísticas acerca de los clientes, las ventas del Servicio y los patrones de tráfico.

